name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./Front-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manage NPM Dependencies
        uses: .github/actions/cache-node-dependencies
        with:
          app-name: "react-app"
          working-directory: "./Front-End"

      - name: Build
        run: npm run build